### PR TITLE
Fixes for #122

### PR DESCRIPTION
**Pull request by khaledhosny**
1. Rewrite autohint.hintFiles() so that the output of hint_compatible_bez_glyphs() is used for reference master as well.
2. Stop adding short line segments to “zero length closepaths”.

### CODE REVIEW

**Comment by miguelsousa** [comment]
@khaledhosny the checks didn't pass

**Comment by khaledhosny** [comment]
Yes, some tests are crashing on the CI machines but not on mine, scratching my head trying to figure out how to debug this…

**Comment by khaledhosny** [comment]
OK, I know knows what is crashing, but no idea why. Still investigation, do not merge.

**Comment by khaledhosny** [comment]
Still not able to reproduce the crashes locally. I even used [Travis Docker image](https://docs.travis-ci.com/user/common-build-problems/#troubleshooting-locally-in-a-docker-image) hoping to replicate the same environment, but no luck.

**Comment by khaledhosny** [comment]
@anthrotype Can you help here? You were able to reproduce similar weird crashes in the past, any chance you can try this branch locally and see if you can reproduce the crashes (they are transient, but no matter how many times I run this locally it doesn’t crash for me).

**Comment by khaledhosny** [comment]
@miguelsousa This should be ready to review once the build finishes. I couldn’t fix the crash (still can’t reproduce it), but I worked around it by partially reverting to the old approach.

**Comment by anthrotype** [comment]
@khaledhosny hey, I was away last week. Do you still need me to try reproduce this locally? Should I revert any commits to repro, if so which ones?

**Comment by khaledhosny** [comment]
Yes, the crash is not fixed yet. Try reverting the last commit on master and see if you can reproduce it.

**Comment by anthrotype** [comment]
I reverted the e09f397ce77a4a7ef9b4afeb987dc5dc9925c42b commit, and run `tox -e py37-cov` using a pyenv-compiled Python 3.7.1 running on my Debian Linux box. All tests passed without crashes.

**Comment by khaledhosny** [comment]
The crashes are flaky (the tests didn’t always crash on CI), try running it a few more times if possible,

**Pull request merged**
