### PR TITLE
travis/appveyor: deploy wheels and sdist to Github on tags

### LINKED ISSUE #98: generated version.h causes problems for Debian build
The generated `version.h` thing mentioned in #82 and #59 is making it difficult for me to build psautohint as a Debian package.

It looks like it wants me to add that `version.h` as a Debian patch but that seems annoying if someone will need to update that patch for every new release and it goes against the "don't change, don't track in version control" warning.

Respectfully, what problem are you trying to solve here?

```
dpkg-buildpackage: info: source package psautohint
dpkg-buildpackage: info: source version 1.7.0-1
dpkg-buildpackage: info: source distribution UNRELEASED
 dpkg-source --before-build psautohint-1.7.0
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean --with python3 --buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:217: python3.6 setup.py clean 
running clean
removing '/<<PKGBUILDDIR>>/.pybuild/cpython3_3.6/build' (and everything under it)
/usr/lib/python3/dist-packages/setuptools_scm/version.py:191: UserWarning: meta invoked without explicit configuration, will use defaults where required.
  "meta invoked without explicit configuration,"
'build/bdist.linux-amd64' does not exist -- can't clean it
'build/scripts-3.6' does not exist -- can't clean it
 dpkg-source -b psautohint-1.7.0
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building psautohint using existing ./psautohint_1.7.0.orig.tar.gz
dpkg-source: info: local changes detected, the modified files are:
 psautohint-1.7.0/libpsautohint/src/version.h
dpkg-source: error: aborting due to unexpected upstream changes, see /tmp/psautohint_1.7.0-1.diff.0HHSDa
dpkg-source: info: you can integrate the local changes with dpkg-source --commit
dpkg-buildpackage: error: dpkg-source -b psautohint-1.7.0 subprocess returned exit status 2
```

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes #98

### CODE REVIEW

**Comment by anthrotype** [comment]
it's using anthrotype's encrypted github token (I can push to the repo so it'll work).
the only way to test this is to merge and tag a new pre-release.

**Comment by khaledhosny** [comment]
Do we want to deploy the wheels or just the sdist? I’d say the later since the wheels are also uploaded to PyPI and there is no much value in uploading them here as well.

**Comment by anthrotype** [comment]
ok let's only upload the sdist to github

**Comment by khaledhosny** [comment]
Sure, please merge.

**Comment by anthrotype** [comment]
it worked https://github.com/adobe-type-tools/psautohint/releases/tag/v1.7.1b4

pity that it's not possible to remove those two default "Source code" links that Github always puts in the release assets. anyway, good enough for me

**Comment by khaledhosny** [comment]
Thanks! Yes, they automatic source links have always been an annoyance.

**Pull request merged**
