### PR TITLE
simple test if incoming list is not empty

### PR DESCRIPTION
**Pull request by typemytype**
fixing #302

### CODE REVIEW

**Comment by frankrolf** [comment]
Frederik and I had a discussion about this – while we understand that many bugs are fixed in https://github.com/iterumllc/psautohint/tree/pyport, some small bugfixes could still make it into the main branch here (which is embedded in RoboFont)

**Comment by skef** [comment]
Seems fine to me.

Any chance of moving some of the booleanOperations stuff forward while we're looking at things?

**Review by skef — APPROVED** [review]
lgtm

**Comment by skef** [comment]
This was never merged and has been superseded by otfautohint in the main afdko repository.

**Pull request closed without merging**
