### PR TITLE
Drop autohintexe wrapper

### PR DESCRIPTION
**Pull request by khaledhosny**
See https://github.com/adobe-type-tools/psautohint/issues/101#issuecomment-418846200

### CODE REVIEW

**Comment by khaledhosny** [comment]
In `__init__.py`.

**Comment by miguelsousa** [comment]
Is it needed? I'd rip that out as well

**Comment by khaledhosny** [comment]
I’m keeping it to be used by AFDKO, see https://github.com/adobe-type-tools/afdko/pull/596, not sure if we can move the definition to AFDKO (not in its current form that relies on `__file__` at least).

**Comment by anthrotype** [comment]
I think it should stay here

**Pull request merged**
